CREATE TABLE users
(
	id BIGSERIAL PRIMARY KEY,
	
	first_name VARCHAR(100) NOT NULL,
	
	last_name VARCHAR(100) NOT NULL,
	
	email VARCHAR(100) NOT NULL UNIQUE,
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)